<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container39iR3cx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container39iR3cx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container39iR3cx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container39iR3cx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container39iR3cx\App_KernelDevDebugContainer([
    'container.build_hash' => '39iR3cx',
    'container.build_id' => '83f73a78',
    'container.build_time' => 1649238825,
], __DIR__.\DIRECTORY_SEPARATOR.'Container39iR3cx');
